name: CI
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        DATABASE: ["mysql", "sqlite"]
    steps:
      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: pip install -U pip
      - run: pip install 'tox>=4.6.0' tox-gh-actions codecov
      - run: tox -v
        env:
          DATABASE_USER: root
          DATABASE_PASSWORD: root
          DJANGO_SETTINGS_MODULE: dfd_tests.settings
      - run: codecov -e TRAVIS_PYTHON_VERSION -e DATABASE
